package com.iamagamedev.mybrandnewgame.constants

object ObjectNames {
    const val ENEMY = "nyanko"
    const val ENEMY_TANK = "tanku_neko"
    const val ENEMY_BAD = "nyanko_dead"
    const val ENEMY_BLOW = "enemy_blow"
    const val ENEMY_DEAD = "enemy_dead"
    const val EVIL_MAGE = "evil_mage"
    const val FLORE = "flore"
    const val FOREST = "forest"
    const val GRASS = "grass"
    const val HERO = "hero"
    const val HERO_BAD = "hero_bad"
    const val HOME = "home"
    const val LAND = "land"
    const val MAGE = "mage"
    const val MAGE_DEAD = "mage_dead"
    const val MAGE_DOWN = "mage_down"
    const val MOUNT = "mount"
    const val OUTSIDE = "outside"
    const val TOWN = "town"
    const val WALL = "wall"
    const val WALL_BAD = "wall_bad"
    const val WOOD = "wood"
    const val FRESCO = "map_flore"
}